### PR TITLE
Hines' Greeting

### PR DESCRIPTION
**Pull request by zkao04**
Hines' Greeting

### CODE REVIEW

**Comment by zkao04** [comment]
Hi, I'm pushing this through my own extended greeting branch

**Comment by zkao04** [comment]
Attempting another pull request

**Comment by zkao04** [comment]
I hope I get it this time

**Review by IkenoXamos — CHANGES_REQUESTED** [review]
Looks like Daiki's Greeting was duplicated. Please resolve.

**Comment by zkao04** [comment]
9th Attempt

**Review by IkenoXamos — CHANGES_REQUESTED** [review]
Daiki's Greeting is duplicated. It is on both lines 7 and 10.

**Comment by zkao04** [comment]
Pulled, committed, and pushed after Daniel

**Comment by zkao04** [comment]
11th Attempt

**Review by IkenoXamos — APPROVED** [review]
Looks good!

**Pull request merged**
